"""
Django settings for anaetainan project.

Generated by 'django-admin startproject' using Django 2.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os
from pathlib import Path
from datetime import datetime

import dj_database_url
from decouple import config, Csv
from django.core.management.utils import get_random_secret_key

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config("SECRET_KEY", default=get_random_secret_key())

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config("DEBUG", default=False, cast=bool)

ALLOWED_HOSTS = config(
    "ALLOWED_HOSTS",
    default="anaetainan.fly.dev",
    cast=Csv(),
)

CSRF_TRUSTED_ORIGINS = config(
    "CSRF_TRUSTED_ORIGINS",
    default="https://anaetainan.fly.dev",
    cast=Csv(),
)

# CORS
# if DEBUG:
#     CORS_ALLOW_CREDENTIALS = config("CORS_ALLOW_CREDENTIALS", default=False, cast=bool)
#     CORS_ALLOWED_ORIGINS = config(
#         "CSRF_TRUSTED_ORIGINS",
#         default="http://localhost:3000",
#         cast=Csv(),
#     )

# Application definition
DJANGO_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
]

THIRD_PARTY_APPS = [
    "django_extensions",
    "whitenoise.runserver_nostatic",
    "floppyforms",
]

# CORS
# if DEBUG:
#     THIRD_PARTY_APPS += ['corsheaders']

LOCAL_APPS = [
    "anaetainan.base",
    "anaetainan.accounts",
    "anaetainan.core",
    "anaetainan.themes",
    "anaetainan.fotos",
    "anaetainan.listapresentes",
    "anaetainan.fornecedores",
]

INSTALLED_APPS = DJANGO_APPS + THIRD_PARTY_APPS + LOCAL_APPS

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

# CORS
# if DEBUG:
#     before_common = MIDDLEWARE.index("django.middleware.common.CommonMiddleware")
#     MIDDLEWARE.insert(before_common, "corsheaders.middleware.CorsMiddleware")

DJ_CASAMENTO_MODO_SAVE_THE_DATE = config(
    "DJ_CASAMENTO_MODO_SAVE_THE_DATE", default=True, cast=bool
)
DJ_CASAMENTO_EXIBIR_HOTEIS = config(
   "DJ_CASAMENTO_EXIBIR_HOTEIS", default=True, cast=bool
)
DJ_CASAMENTO_STD_MSG1 = config("DJ_CASAMENTO_STD_MSG1", default="SAVE THE DATE")
DJ_CASAMENTO_STD_MSG2 = config(
    "DJ_CASAMENTO_STD_MSG2",
    default="Are getting married and will be pleased with your presence!",
)
DJ_CASAMENTO_STD_MSG3 = config("DJ_CASAMENTO_STD_MSG3", default="Invitation to follow")

# Nome dos noivos
DJ_CASAMENTO_DE_UM_LADO = "Ana"
DJ_CASAMENTO_DO_OUTRO = "Tainan"

# Dia e local
DJ_CASAMENTO_DATA = "2024-11-16 17:00:00".replace("-", "/")
DJ_CASAMENTO_LOCAL = "Capela Nossa Sra da Paz"
DJ_CASAMENTO_CIDADE = "Juiz de Fora/MG"
DJ_CASAMENTO_DATE = datetime.strptime(DJ_CASAMENTO_DATA, "%Y/%m/%d %H:%M:%S")

# Outros
DJ_CASAMENTO_JA_ACONTECEU = datetime.today() >= DJ_CASAMENTO_DATE
DJ_CASAMENTO_EMAIL_CONTATO = "contato@tabmarketing.com.br"
DJ_CASAMENTO_FONE_CONTATO = "(32) 99142-1203"
DJ_CASAMENTO_SERVER = "casamentobiaetainan.com.br"

# EMAIL
DJ_EMAIL_NOTIFICATIONS = config("DJ_EMAIL_NOTIFICATIONS", default=False, cast=bool)
DJ_EMAIL_FROM = "anaetainan@example.com"
DJ_EMAIL_DISTRIBUTION_LIST = ["anaetainan@example.com"]

ROOT_URLCONF = "anaetainan.anaetainan.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "anaetainan.core.context_processors.configuracoes_processor",
            ],
        },
    },
]

WSGI_APPLICATION = "anaetainan.anaetainan.wsgi.application"

AUTH_USER_MODEL = "accounts.User"

# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

DATABASE_URL = config("DATABASE_URL")

DATABASES = {
    "default": dj_database_url.parse(
        DATABASE_URL,
        conn_max_age=600,
        conn_health_checks=True,
    )
}

# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = config("LANGUAGE_CODE", default="pt-br")

TIME_ZONE = config("TIME_ZONE", default="UTC")

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = config(
    "DJANGO_STATIC_ROOT", default=os.path.join(BASE_DIR.parent, "static")
)

# STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"
STORAGES = {
    "default": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

LOG_LEVEL = config("LOG_LEVEL", default="INFO")

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{levelname} {asctime} {module}:{lineno} {process:d} {message}",
            "style": "{",
        },
        "console": {
            "format": "{levelname} {asctime} {module}:{lineno} {process:d} {message}",
            "style": "{",
        },
        "django": {
            "format": "{levelname} {asctime} {module}:{lineno} {process:d} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {"class": "logging.StreamHandler", "formatter": "verbose"},
        "django": {"class": "logging.StreamHandler", "formatter": "verbose"},
    },
    "loggers": {
        "": {
            "level": LOG_LEVEL,
            "handlers": [
                "console",
            ],
        },
        "django.server": {
            "level": LOG_LEVEL,
            "handlers": [
                "console",
            ],
        },
    },
}

# LOGGING = {
#     'version': 1,
#     'formatters': {
#         'verbose': {
#             'format': '%(levelname)s %(asctime)s %(module)s %(process)d %(thread)d %(message)s'
#         },
#         'simple': {
#             'format': '%(levelname)s %(message)s'
#         },
#     },
#     'filters': {
#         'require_debug_false': {
#             '()': 'django.utils.log.RequireDebugFalse',
#         }
#     },
#     'handlers': {
#         'console': {
#             'level': 'DEBUG',
#             'class': 'logging.StreamHandler',
#             'formatter': 'simple'
#         },
#         'file': {
#             'level': 'DEBUG',
#             'class': 'logging.FileHandler',
#             'filename': os.getenv('DJANGO_LOG_FILE', './anaetainan.log'),
#             'formatter': 'simple'
#         },
#     },
#     'loggers': {
#         '': {
#             'handlers': ['file'],
#             'level': 'DEBUG' if DEBUG else 'INFO',
#             'propagate': True,
#         },
#         'django': {
#             'handlers': ['file'],
#             'level': 'DEBUG' if DEBUG else 'INFO',
#             'propagate': True,
#         },
#     }
# }

# if DEBUG:
#     # make all loggers use the console.
#     for logger in LOGGING['loggers']:
#         LOGGING['loggers'][logger]['handlers'] = ['console']
