# Generated by Django 4.1.7 on 2024-03-22 01:34

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Fotos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "titulo",
                    models.CharField(
                        blank=True, default="", max_length=128, verbose_name="Titulo"
                    ),
                ),
                (
                    "imagem",
                    models.ImageField(
                        blank=True,
                        default="",
                        upload_to="fotos/",
                        verbose_name="imagem",
                    ),
                ),
                ("ordem", models.IntegerField(blank=True, default=1, null=True)),
            ],
            options={
                "verbose_name": "Foto",
                "verbose_name_plural": "Fotos",
            },
        ),
    ]
