# Generated by Django 4.1.7 on 2024-05-08 18:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fotos", "0002_alter_fotos_imagem"),
    ]

    operations = [
        migrations.AddField(
            model_name="fotos",
            name="imagem_data",
            field=models.TextField(blank=True, null=True, verbose_name="imagem data"),
        ),
    ]
