# Generated by Django 4.1.7 on 2024-03-22 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Presente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "titulo",
                    models.CharField(
                        blank=True, default="", max_length=128, verbose_name="Título"
                    ),
                ),
                (
                    "descricao",
                    models.TextField(
                        blank=True, default="", verbose_name="Descrição do presente"
                    ),
                ),
                (
                    "imagem",
                    models.ImageField(
                        blank=True,
                        default="",
                        upload_to="presentes",
                        verbose_name="imagem",
                    ),
                ),
                (
                    "valor",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=12,
                        verbose_name="Valor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Presente",
                "ordering": ("valor",),
            },
        ),
        migrations.CreateModel(
            name="IntencaoDePresente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateTimeField(auto_now_add=True)),
                (
                    "nome",
                    models.CharField(
                        default="", max_length=128, verbose_name="Seu nome"
                    ),
                ),
                ("email", models.EmailField(max_length=128, verbose_name="e-mail")),
                (
                    "banco",
                    models.CharField(
                        choices=[
                            ("BRADESCO", "Bradesco"),
                            ("ITAU", "Itaú"),
                            ("SANTANDER", "Santander"),
                            ("NUBANK", "Nubank"),
                        ],
                        default="ITAU",
                        max_length=16,
                        verbose_name="Transferir para o banco",
                    ),
                ),
                (
                    "mensagem",
                    models.TextField(
                        blank=True, default="", verbose_name="Mensagem para o casal"
                    ),
                ),
                (
                    "valor",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=12,
                        verbose_name="Valor",
                    ),
                ),
                ("pagamento_ok", models.BooleanField(default=False)),
                ("saque_ok", models.BooleanField(default=False)),
                ("agradecimento_ok", models.BooleanField(default=False)),
                ("foto_agradecimento_ok", models.BooleanField(default=False)),
                (
                    "presente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="listapresentes.presente",
                        verbose_name="presente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Intenção de Presente",
                "ordering": (
                    "pagamento_ok",
                    "banco",
                    "saque_ok",
                    "agradecimento_ok",
                    "-id",
                ),
            },
        ),
    ]
