# Generated by Django 4.1.7 on 2024-03-28 00:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("listapresentes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="presente",
            name="imagem",
            field=models.URLField(
                blank=True, default="", max_length=1024, verbose_name="imagem"
            ),
        ),
    ]
