# Generated by Django 4.1.7 on 2024-04-18 18:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("listapresentes", "0002_alter_presente_imagem"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContaParaRecebimento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "banco",
                    models.CharField(
                        blank=True, default="", max_length=128, verbose_name="Banco"
                    ),
                ),
                (
                    "agencia",
                    models.CharField(
                        blank=True, default="", max_length=32, verbose_name="Agencia"
                    ),
                ),
                (
                    "conta",
                    models.CharField(
                        blank=True, default="", max_length=32, verbose_name="Conta"
                    ),
                ),
                (
                    "favorecido",
                    models.CharField(
                        blank=True, default="", max_length=64, verbose_name="Favorecido"
                    ),
                ),
                (
                    "cpf",
                    models.CharField(
                        blank=True, default="", max_length=32, verbose_name="Favorecido"
                    ),
                ),
                (
                    "chave_pix",
                    models.CharField(
                        blank=True, default="", max_length=128, verbose_name="Chave PIX"
                    ),
                ),
            ],
            options={
                "verbose_name": "Contas",
                "ordering": ("id",),
            },
        ),
    ]
