# Generated by Django 4.1.7 on 2024-04-18 19:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("listapresentes", "0004_alter_contapararecebimento_cpf_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contapararecebimento",
            old_name="banco",
            new_name="nome_banco",
        ),
    ]
