# Generated by Django 4.1.7 on 2024-03-20 17:55

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Fornecedor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        default="", max_length=128, verbose_name="Fornecedor"
                    ),
                ),
                (
                    "categoria",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=128,
                        verbose_name="Categoria (Buffet, Som etc..)",
                    ),
                ),
                (
                    "contato",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=128,
                        verbose_name="Nome do Contato",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=128, verbose_name="e-mail"
                    ),
                ),
                (
                    "fone",
                    models.CharField(
                        blank=True, default="", max_length=32, verbose_name="Fone"
                    ),
                ),
                (
                    "fone2",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=32,
                        verbose_name="Fone (alternativo)",
                    ),
                ),
                (
                    "site",
                    models.URLField(blank=True, max_length=256, verbose_name="Site"),
                ),
                (
                    "notas",
                    models.TextField(blank=True, default="", verbose_name="Notas"),
                ),
                (
                    "endereco",
                    models.TextField(blank=True, default="", verbose_name="Endereço"),
                ),
            ],
            options={
                "verbose_name": "Fornecedor",
                "ordering": ("nome",),
            },
        ),
    ]
